window.TRIP = {
  title: "港澳四日",
  subtitle: "8 月底 · 情侣出片指南",
  route: "北京 → 深圳探友 → 香港 → 澳门 → 蛇口回深圳",
  spots: [
    {
      id: "taikwun",
      city: "hk",
      area: "中环",
      name: "大馆",
      en: "Tai Kwun",
      enter: "港铁中环站 D2 步行约 8 分钟。园区免费，不用预约。部分展览和 JC Contemporary 要另买票，现场或官网即可。大约 10:00–23:00 开放。",
      duration: "1–1.5 小时",
      note: "8 月室内冷气足，带薄外套。免费区域已经够逛、够拍。展厅和监狱旧址保持安静，别用灯、别挡路。",
      xhs: ["香港大馆拍照", "大馆红砖情侣", "大馆旋转楼梯"],
      fallback: "#6b3a2a",
      map: "Tai Kwun Central Hong Kong",
      lat: 22.2814,
      lng: 114.1540,
      day: 1
    },
    {
      id: "escalator",
      city: "hk",
      area: "中环 / 苏豪",
      name: "半山扶梯 · 石板街",
      en: "Mid-Levels Escalator",
      enter: "大馆出来沿荷李活道、嘉咸街接半山自动扶梯。公共设施，免费，不用预约。",
      duration: "30–40 分钟",
      note: "扶梯主要单向：大约上午 6:00–10:00 向下，其余时间向上，别逆行挡路。街拍点到为止，不要长时间占台阶。",
      xhs: ["半山扶梯拍照", "石板街香港", "嘉咸街壁画"],
      fallback: "#c45c2a",
      map: "Mid-Levels Escalator Hong Kong",
      lat: 22.2830,
      lng: 114.1547,
      day: 1
    },
    {
      id: "kennedy",
      city: "hk",
      area: "坚尼地城",
      name: "坚尼地城",
      en: "Kennedy Town",
      enter: "港铁坚尼地城站 C 出口。游泳池在西宁街，外观和周边街道免费拍，不用预约；进场游泳要门票和泳衣。卑路乍湾海滨长廊、科士街楼梯都是公共空间，免费。",
      duration: "1–1.5 小时",
      note: "先拍游泳池那栋白建筑和楼群同框，再沿海滨走到卑路乍湾。8 月很晒，带帽子。泳池不要翻栏杆、不要影响泳客。科士街是民居楼梯，拍完就走。想拍日落就改晚上来，和第 1 天卢吉道冲突。",
      xhs: ["坚尼地城游泳池拍照", "卑路乍湾海滨", "科士街楼梯"],
      fallback: "#3d7a8c",
      map: "Kennedy Town Swimming Pool Hong Kong",
      lat: 22.2813,
      lng: 114.1265,
      day: 1
    },
    {
      id: "hku",
      city: "hk",
      area: "薄扶林",
      name: "香港大学",
      en: "The University of Hong Kong",
      enter: "港铁香港大学站 A1 出口沿指示上校园。本部大楼、陆佑堂外观和校园道路免费拍，不用预约。图书馆、课室、宿舍不对外开放。",
      duration: "40–50 分钟",
      note: "先拍本部大楼红砖和棕榈树，再看陆佑堂。校园有坡，穿运动鞋。上课时段保持安静，不要挡路、不要进楼拍。8 月底暑假人少，更好拍。",
      xhs: ["香港大学本部大楼", "港大拍照", "港大陆佑堂"],
      fallback: "#5c3d2e",
      map: "HKU Main Building Pokfulam",
      lat: 22.2840,
      lng: 114.1378,
      day: 1
    },
    {
      id: "lugard",
      city: "hk",
      area: "太平山",
      name: "卢吉道观景台",
      en: "Lugard Road Lookout",
      enter: "卢吉道步行径免费，不用预约。上山可坐山顶缆车（建议官网预约）或 15 路巴士。从凌霄阁沿卢吉道走约 10–15 分钟到观景缺口。",
      duration: "1.5–2 小时（含上山）",
      note: "不要只去凌霄阁排队。8 月底日落大约 18:50，建议 17:30 后到。山路有蚊，带薄外套。雨天路滑。",
      xhs: ["卢吉道观景台", "太平山卢吉道日落", "卢吉道情侣"],
      fallback: "#1d3a4a",
      map: "Lugard Road Lookout Victoria Peak",
      lat: 22.2712,
      lng: 114.1482,
      day: 1
    },
    {
      id: "starferry",
      city: "hk",
      area: "维港",
      name: "天星小轮",
      en: "Star Ferry",
      enter: "中环天星码头 ↔ 尖沙咀天星码头。现场买票或拍八达通，不用预约，几分钟一班。",
      duration: "单程约 10 分钟",
      note: "坐上层、靠海一侧。手机广角别开太狠。风大，帽子和薄外套收好。",
      xhs: ["天星小轮拍照", "天星小轮上层", "维港天星小轮"],
      fallback: "#2c5f6e",
      map: "Star Ferry Tsim Sha Tsui Pier",
      lat: 22.2937,
      lng: 114.1684,
      day: 1
    },
    {
      id: "harbour",
      city: "hk",
      area: "尖沙咀",
      name: "钟楼 · 维港海滨",
      en: "Tsim Sha Tsui Promenade",
      enter: "天星小轮下船即到，或港铁尖沙咀站 / 尖东站。海滨和钟楼外观免费，不用预约。",
      duration: "45 分钟–1 小时",
      note: "幻彩咏香江大约 20:00。晚上人多，沿堤岸往西九方向会疏一点。8 月很热，拍完可进海港城。",
      xhs: ["尖沙咀钟楼夜景", "维港海滨拍照", "幻彩咏香江"],
      fallback: "#0f2740",
      map: "Tsim Sha Tsui Clock Tower Hong Kong",
      lat: 22.2938,
      lng: 114.1696,
      day: 1
    },
    {
      id: "mplus",
      city: "hk",
      area: "西九",
      name: "M+ 博物馆",
      en: "M+",
      enter: "尖沙咀海滨向西步行 15–20 分钟，或港铁柯士甸站。艺术公园和外观免费、不用预约。进馆要门票，周末建议官网提前买。",
      duration: "园区 40 分钟；进馆约 1.5 小时",
      note: "只拍外观和园区不必买票。台风或暴雨可把这里当室内备选。馆内按展览规定，通常不能用闪光灯。",
      xhs: ["M+博物馆拍照", "西九M+大字", "M+艺术公园"],
      fallback: "#4a5560",
      map: "M+ Museum West Kowloon",
      lat: 22.3017,
      lng: 114.1570,
      day: 1
    },
    {
      id: "monster",
      city: "hk",
      area: "鲗鱼涌",
      name: "海山楼（怪兽大厦）",
      en: "Yick Cheong Building",
      enter: "港铁太古站 D 出口步行约 5 分钟，英皇道 1028 号一带。这是民居天井，没有门票，也不能预约，不是景区。",
      duration: "10–20 分钟",
      note: "安静拍、不挡路、不用灯、不躺、不喊。有时会劝离，尊重即走。不要跟居民对拍。",
      xhs: ["海山楼怪兽大厦", "鲗鱼涌海山楼拍照", "怪兽大厦天井"],
      fallback: "#d4786a",
      map: "Yick Cheong Building Quarry Bay",
      lat: 22.2850,
      lng: 114.2164,
      day: 3
    },
    {
      id: "mongkok",
      city: "hk",
      area: "旺角",
      name: "弥敦道天桥",
      en: "Nathan Road Footbridge",
      enter: "港铁旺角站 E 出口一带天桥，或豉油街、西洋菜南街。公共街道，免费，不用预约。",
      duration: "30–40 分钟",
      note: "8 月下午暴晒，建议吃饭前后或晚上再去。人多、注意随身物品。天桥上别长时间挡路。",
      xhs: ["弥敦道天桥夜景", "旺角天桥拍照", "旺角霓虹"],
      fallback: "#7a1f2b",
      map: "Nathan Road Mong Kok footbridge",
      lat: 22.3193,
      lng: 114.1697,
      day: 3
    },
    {
      id: "disney",
      city: "hk",
      area: "大屿山",
      name: "香港迪士尼乐园",
      en: "Hong Kong Disneyland",
      enter: "必须提前购买指定日期门票（官网或 Klook），8 月底现场很容易没有。港铁欣澳站换乘迪士尼线，开园前到。可选付费快速通行。",
      duration: "一整天（约 8–10 小时）",
      note: "出发前下载官方 App，看排队和巡游时间。中午湿热，多进室内。城堡和大街人少时先拍。行李尽量少带。",
      xhs: ["香港迪士尼城堡拍照", "港迪美国小镇大街", "港迪城堡情侣"],
      fallback: "#2f6b4f",
      map: "Hong Kong Disneyland Castle",
      lat: 22.3132,
      lng: 114.0415,
      day: 2
    },
    {
      id: "stpaul",
      city: "mo",
      area: "澳门半岛",
      name: "大三巴牌坊",
      en: "Ruins of St. Paul's",
      enter: "住半岛可步行，或巴士到大三巴／板樟堂街。牌坊广场免费，不用预约。牌坊后博物馆若开放，可能收小额门票。",
      duration: "30–40 分钟",
      note: "请第 4 天 8:30 前到。11:00 后几乎拍不到两人。侧拍、低机位，不要站正中间跟人堆叠在一起。",
      xhs: ["大三巴清晨拍照", "大三巴情侣机位", "大三巴牌坊侧拍"],
      fallback: "#c4b49a",
      map: "Ruins of St Paul's Macau",
      lat: 22.1974,
      lng: 113.5407,
      day: 4
    },
    {
      id: "paixao",
      city: "mo",
      area: "澳门半岛",
      name: "恋爱巷",
      en: "Travessa da Paixão",
      enter: "大三巴牌坊右侧步行约 2 分钟。公共巷弄，免费，不用预约。",
      duration: "15–20 分钟",
      note: "巷子很短，排队拍照请快。旁边疯堂斜巷人更少、墙面同样好拍。不要堵住整条巷。",
      xhs: ["澳门恋爱巷", "恋爱巷路牌", "疯堂斜巷"],
      fallback: "#e8b4a2",
      map: "Travessa da Paixão Macau",
      lat: 22.1970,
      lng: 113.5403,
      day: 4
    },
    {
      id: "senado",
      city: "mo",
      area: "澳门半岛",
      name: "议事亭前地 · 玫瑰堂",
      en: "Senado Square & St. Dominic's",
      enter: "大三巴沿大三巴街往下走 8–10 分钟。广场免费。玫瑰堂通常免费参观，不用预约；保持安静，不要开闪光灯。",
      duration: "40 分钟",
      note: "和大三巴、恋爱巷是同一条步行线，不要拆开跑。正午地面反光强、人多，早晨或晚饭后更合适。",
      xhs: ["议事亭前地波浪纹", "玫瑰堂澳门拍照", "议事亭前地"],
      fallback: "#d4a017",
      map: "Senado Square Macau",
      lat: 22.1935,
      lng: 113.5399,
      day: 4
    },
    {
      id: "penha",
      city: "mo",
      area: "澳门半岛",
      name: "主教山小堂",
      en: "Penha Chapel",
      enter: "巴士到西望洋圣堂／主教山，或打的。小堂和观景台免费，不用预约。进堂请衣着端庄。",
      duration: "45 分钟",
      note: "山路有点陡。第 3 天下午大三巴人最多时，改来这里更值。风大，注意安全，不要翻越栏杆。",
      xhs: ["主教山小堂", "西望洋圣堂拍照", "主教山情侣"],
      fallback: "#8fa3b0",
      map: "Capela de Nossa Senhora da Penha Macau",
      lat: 22.1865,
      lng: 113.5369,
      day: 3
    },
    {
      id: "parisian",
      city: "mo",
      area: "路氹",
      name: "巴黎人 · 伦敦人",
      en: "The Parisian & The Londoner",
      enter: "酒店公共区域免费进入，不用预约。巴黎人花园大约 10:00 开门。铁塔观景台若收费，以现场告示为准。可坐氹仔免费接驳或酒店穿梭巴士。",
      duration: "1–1.5 小时",
      note: "晚上铁塔整点灯光更好看。台风天室内走廊和商场可当备选。赌场区域注意着装，部分地方限制拍照。",
      xhs: ["澳门巴黎人铁塔", "伦敦人天桥看铁塔", "巴黎人花园"],
      fallback: "#3b2d4a",
      map: "The Parisian Macao",
      lat: 22.1454,
      lng: 113.5636,
      day: 3
    },
    {
      id: "taipa",
      city: "mo",
      area: "氹仔",
      name: "官也街",
      en: "Rua do Cunha",
      enter: "氹仔市区步行即到，近手信店和葡挞店。公共街道，免费，不用预约。",
      duration: "30–40 分钟",
      note: "主要为了吃和手信，不是第一出片点。周末下午极挤。晚上灯亮起来更有氛围。看管背包。",
      xhs: ["官也街夜景", "氹仔官也街", "官也街手信"],
      fallback: "#5c4033",
      map: "Rua do Cunha Taipa",
      lat: 22.1527,
      lng: 113.5559,
      day: 4
    }
  ],
  days: [
    {
      id: 1,
      title: "香港岛 + 维港",
      stay: "尖沙咀",
      from: "深圳福田口岸",
      where: "坚尼地城、港大、中环、太平山、维港",
      path: "福田口岸 → 坚尼地城 → 港大 → 中环大馆 / 半山 → 卢吉道日落 → 天星小轮 → 维港钟楼",
      prep: [
        { item: "游客版八达通加到手机钱包", need: "建议提前", xhs: "八达通游客版" },
        { item: "山顶缆车", need: "建议官网预约；也可坐 15 路巴士不用预约", xhs: "山顶缆车预约" },
        { item: "坚尼地城、港大、大馆、半山扶梯、天星小轮、维港", need: "免费，不用预约" },
        { item: "兰芳园午饭", need: "不用订，现场排队" }
      ],
      beats: [
        { id: "d1a", time: "08:00", type: "commute", name: "深圳地铁 4 / 10 号线 → 福田口岸", lat: 22.5204, lng: 114.0682 },
        { id: "d1b", time: "08:15", type: "commute", name: "福田口岸过关（出闸落马洲站）", lat: 22.5150, lng: 114.0660 },
        { id: "d1c", time: "08:50", type: "commute", name: "东铁线 落马洲 → 金钟，转港岛线到坚尼地城 · 约 65 分钟", lat: 22.2813, lng: 114.1289 },
        { id: "d1kt", time: "10:00", type: "spot", name: "坚尼地城", spotId: "kennedy" },
        { id: "d1hk", time: "10:55", type: "commute", name: "港岛线 坚尼地城 → 香港大学 · 约 3 分钟", lat: 22.2840, lng: 114.1378 },
        { id: "d1hku", time: "11:00", type: "spot", name: "香港大学", spotId: "hku" },
        { id: "d1cc", time: "11:50", type: "commute", name: "港岛线 香港大学 → 中环 · 约 8 分钟", lat: 22.2819, lng: 114.1582 },
        { id: "d1d", time: "12:00", type: "spot", name: "大馆", spotId: "taikwun" },
        { id: "d1e", time: "13:10", type: "commute", name: "步行 荷李活道 → 嘉咸街 · 约 8 分钟", lat: 22.2830, lng: 114.1547 },
        { id: "d1f", time: "13:20", type: "spot", name: "半山扶梯 · 石板街", spotId: "escalator" },
        { id: "d1g", time: "14:20", type: "meal", name: "午饭 · 兰芳园（中环结志街）", lat: 22.2839, lng: 114.1550, xhs: "兰芳园 中环" },
        { id: "d1h", time: "16:00", type: "commute", name: "步行至花园道，山顶缆车上山（可改 15 路巴士）", lat: 22.2774, lng: 114.1544 },
        { id: "d1i", time: "16:50", type: "spot", name: "卢吉道观景台", spotId: "lugard" },
        { id: "d1j", time: "19:15", type: "commute", name: "山顶缆车下山至中环", lat: 22.2774, lng: 114.1544 },
        { id: "d1k", time: "19:40", type: "commute", name: "天星小轮 中环 → 尖沙咀 · 约 10 分钟", lat: 22.2937, lng: 114.1684 },
        { id: "d1l", time: "20:00", type: "spot", name: "钟楼 · 维港海滨", spotId: "harbour" },
        { id: "d1m", time: "21:15", type: "hotel", name: "尖沙咀酒店", lat: 22.2976, lng: 114.1722 }
      ]
    },
    {
      id: 2,
      title: "港迪",
      stay: "尖沙咀",
      from: "尖沙咀酒店",
      where: "香港迪士尼（一整天）",
      path: "尖沙咀 → 美孚 / 屯马线 → 欣澳 → 迪士尼线 → 园内一整天 → 回尖沙咀",
      prep: [
        { item: "香港迪士尼指定日门票", need: "必须提前买（官网或 Klook），8 月底现场很容易没有", xhs: "香港迪士尼门票" },
        { item: "Disney 官方 App", need: "出发前下载，看排队和巡游" },
        { item: "付费快速通行", need: "可选，现场或网上" },
        { item: "园内午饭晚饭", need: "不用订，App 看排队" }
      ],
      beats: [
        { id: "d2a", time: "08:10", type: "commute", name: "荃湾线 尖沙咀 → 美孚，转屯马线 → 欣澳，转迪士尼线 · 约 55–70 分钟", lat: 22.3132, lng: 114.0415 },
        { id: "d2b", time: "09:20", type: "spot", name: "香港迪士尼乐园", spotId: "disney" },
        { id: "d2c", time: "12:30", type: "meal", name: "午饭 · 美国小镇大街", lat: 22.3136, lng: 114.0428, xhs: "港迪美国小镇大街吃饭" },
        { id: "d2d", time: "18:00", type: "meal", name: "晚饭 · 园内", lat: 22.3128, lng: 114.0410, xhs: "香港迪士尼晚餐" },
        { id: "d2e", time: "20:30", type: "commute", name: "迪士尼线 → 欣澳，转屯马线 / 东涌线回尖沙咀 · 约 60 分钟", lat: 22.2976, lng: 114.1722 },
        { id: "d2f", time: "21:40", type: "hotel", name: "尖沙咀酒店", lat: 22.2976, lng: 114.1722 }
      ]
    },
    {
      id: 3,
      title: "港风 → 澳门",
      stay: "路氹",
      from: "尖沙咀（退房）",
      where: "海山楼、旺角、主教山、路氹",
      path: "海山楼 → 旺角早茶 / 天桥 → 上环坐船 → 主教山 → 巴黎人 → 官也街",
      prep: [
        { item: "尖沙咀酒店退房", need: "行李寄存或带上船" },
        { item: "富临饭店早茶", need: "周末建议提前订位", xhs: "富临饭店订位" },
        { item: "喷射飞航 上环 → 澳门外港", need: "必须提前订票", xhs: "喷射飞航订票" },
        { item: "海山楼、弥敦道天桥、主教山、巴黎人、官也街", need: "免费，不用预约" }
      ],
      beats: [
        { id: "d3a", time: "08:00", type: "hotel", name: "尖沙咀酒店退房", lat: 22.2976, lng: 114.1722 },
        { id: "d3b", time: "08:10", type: "commute", name: "荃湾线 尖沙咀 → 旺角，转观塘线到太古 · 约 25 分钟", lat: 22.2850, lng: 114.2164 },
        { id: "d3c", time: "08:40", type: "spot", name: "海山楼（怪兽大厦）", spotId: "monster" },
        { id: "d3d", time: "09:10", type: "commute", name: "观塘线 太古 → 旺角 · 约 20 分钟", lat: 22.3193, lng: 114.1697 },
        { id: "d3e", time: "09:40", type: "meal", name: "早茶 · 富临饭店（旺角）", lat: 22.3178, lng: 114.1702, xhs: "富临饭店 旺角" },
        { id: "d3f", time: "11:00", type: "spot", name: "弥敦道天桥", spotId: "mongkok" },
        { id: "d3g", time: "12:10", type: "commute", name: "荃湾线 旺角 → 中环，步行至上环港澳码头 · 约 25 分钟", lat: 22.2878, lng: 114.1512 },
        { id: "d3h", time: "13:00", type: "commute", name: "喷射飞航 上环 → 澳门外港 · 约 60 分钟", lat: 22.1967, lng: 113.5595 },
        { id: "d3i", time: "14:20", type: "commute", name: "的士 外港 → 主教山 · 约 15 分钟", lat: 22.1865, lng: 113.5369 },
        { id: "d3j", time: "14:40", type: "spot", name: "主教山小堂", spotId: "penha" },
        { id: "d3k", time: "16:40", type: "commute", name: "的士 主教山 → 路氹巴黎人 · 约 20 分钟", lat: 22.1454, lng: 113.5636 },
        { id: "d3l", time: "17:10", type: "spot", name: "巴黎人 · 伦敦人", spotId: "parisian" },
        { id: "d3m", time: "20:30", type: "meal", name: "晚饭 · 巴黎人 / 伦敦人", lat: 22.1458, lng: 113.5628, xhs: "澳门巴黎人餐厅" },
        { id: "d3n", time: "21:30", type: "commute", name: "接驳或的士 → 官也街 · 约 10 分钟", lat: 22.1527, lng: 113.5559 },
        { id: "d3o", time: "21:40", type: "spot", name: "官也街", spotId: "taipa" },
        { id: "d3p", time: "22:20", type: "hotel", name: "路氹酒店", lat: 22.1458, lng: 113.5628 }
      ]
    },
    {
      id: 4,
      title: "澳门清晨 → 蛇口",
      stay: "回深圳",
      from: "路氹酒店",
      where: "大三巴、恋爱巷、议事亭，中午船回蛇口",
      path: "路氹 → 大三巴 → 恋爱巷 → 议事亭 → 外港码头 → 船回蛇口过关",
      prep: [
        { item: "大三巴、恋爱巷、议事亭", need: "免费不用预约，请 8:30 前到大三巴" },
        { item: "大利来猪扒包", need: "不用订，早上去排队更短" },
        { item: "喷射飞航 澳门外港 → 蛇口", need: "必须提前订票，留过关和去机场时间", xhs: "澳门到蛇口船票" },
        { item: "回内地过关", need: "通行证 + 深圳边检，不要再进香港" }
      ],
      beats: [
        { id: "d4a", time: "07:30", type: "commute", name: "的士 / 酒店接驳 路氹 → 大三巴 · 约 25 分钟", lat: 22.1974, lng: 113.5407 },
        { id: "d4b", time: "08:00", type: "spot", name: "大三巴牌坊", spotId: "stpaul" },
        { id: "d4c", time: "08:40", type: "commute", name: "步行 · 约 2 分钟", lat: 22.1970, lng: 113.5403 },
        { id: "d4d", time: "08:42", type: "spot", name: "恋爱巷", spotId: "paixao" },
        { id: "d4e", time: "09:10", type: "commute", name: "步行大三巴街下山 · 约 8 分钟", lat: 22.1935, lng: 113.5399 },
        { id: "d4f", time: "09:20", type: "spot", name: "议事亭前地 · 玫瑰堂", spotId: "senado" },
        { id: "d4g", time: "10:20", type: "meal", name: "猪扒包 · 大利来（议事亭附近）", lat: 22.1938, lng: 113.5405, xhs: "大利来猪扒包" },
        { id: "d4h", time: "11:30", type: "commute", name: "的士 议事亭 → 外港客运码头 · 约 12 分钟", lat: 22.1967, lng: 113.5595 },
        { id: "d4i", time: "12:00", type: "commute", name: "喷射飞航 澳门外港 → 蛇口 · 约 60 分钟", lat: 22.4792, lng: 113.9128 },
        { id: "d4j", time: "13:10", type: "commute", name: "蛇口邮轮母港过关", lat: 22.4792, lng: 113.9128 }
      ]
    }
  ]
};

