window.TRIP = {
  title: "港澳四日",
  subtitle: "8 月底 · 情侣出片指南",
  route: "北京 → 深圳探友 → 香港 → 澳门 → 蛇口回深圳",
  spots: [
    {
      id: "taikwun",
      city: "hk",
      area: "中环",
      name: "大馆",
      en: "Tai Kwun",
      enter: "港铁中环站 D2 步行约 8 分钟。园区免费，不用预约。部分展览和 JC Contemporary 要另买票，现场或官网即可。大约 10:00–23:00 开放。",
      duration: "1–1.5 小时",
      note: "8 月室内冷气足，带薄外套。免费区域已经够逛、够拍。展厅和监狱旧址保持安静，别用灯、别挡路。",
      xhs: ["香港大馆拍照", "大馆红砖情侣", "大馆旋转楼梯"],
      photo: "Tai Kwun Parade Ground 201806.jpg",
      img: "photos/taikwun.jpg",
      fallback: "#6b3a2a",
      map: "Tai Kwun Central Hong Kong",
      lat: 22.2814,
      lng: 114.1540,
      day: 1
    },
    {
      id: "escalator",
      city: "hk",
      area: "中环 / 苏豪",
      name: "半山扶梯 · 石板街",
      en: "Mid-Levels Escalator",
      enter: "大馆出来沿荷李活道、嘉咸街接半山自动扶梯。公共设施，免费，不用预约。",
      duration: "30–40 分钟",
      note: "扶梯主要单向：大约上午 6:00–10:00 向下，其余时间向上，别逆行挡路。街拍点到为止，不要长时间占台阶。",
      xhs: ["半山扶梯拍照", "石板街香港", "嘉咸街壁画"],
      photo: "Central-Mid-Levels Escalator and Walkway System 20-05-2022.jpg",
      img: "photos/escalator.jpg",
      fallback: "#c45c2a",
      map: "Mid-Levels Escalator Hong Kong",
      lat: 22.2830,
      lng: 114.1547,
      day: 1
    },
    {
      id: "kennedy",
      city: "hk",
      area: "坚尼地城",
      name: "坚尼地城",
      en: "Kennedy Town",
      enter: "港铁坚尼地城站 C 出口。游泳池在西宁街，外观和周边街道免费拍，不用预约；进场游泳要门票和泳衣。卑路乍湾海滨长廊、科士街楼梯都是公共空间，免费。",
      duration: "1–1.5 小时",
      note: "先拍游泳池那栋白建筑和楼群同框，再沿海滨走到卑路乍湾。8 月很晒，带帽子。泳池不要翻栏杆、不要影响泳客。科士街是民居楼梯，拍完就走。想拍日落就改晚上来，和第 1 天卢吉道冲突。",
      xhs: ["坚尼地城游泳池拍照", "卑路乍湾海滨", "科士街楼梯"],
      photo: "Kennedy Town Swimming Pool 09-03-2024.jpg",
      img: "photos/kennedy.jpg",
      fallback: "#3d7a8c",
      map: "Kennedy Town Swimming Pool Hong Kong",
      lat: 22.2813,
      lng: 114.1265,
      day: 1
    },
    {
      id: "hku",
      city: "hk",
      area: "薄扶林",
      name: "香港大学",
      en: "The University of Hong Kong",
      enter: "港铁香港大学站 A1 出口沿指示上校园。本部大楼、陆佑堂外观和校园道路免费拍，不用预约。图书馆、课室、宿舍不对外开放。",
      duration: "40–50 分钟",
      note: "先拍本部大楼红砖和棕榈树，再看陆佑堂。校园有坡，穿运动鞋。上课时段保持安静，不要挡路、不要进楼拍。8 月底暑假人少，更好拍。",
      xhs: ["香港大学本部大楼", "港大拍照", "港大陆佑堂"],
      photo: "University of Hong Kong Main Building.jpg",
      img: "photos/hku.jpg",
      fallback: "#5c3d2e",
      map: "HKU Main Building Pokfulam",
      lat: 22.2840,
      lng: 114.1378,
      day: 1
    },
    {
      id: "lugard",
      city: "hk",
      area: "太平山",
      name: "卢吉道观景台",
      en: "Lugard Road Lookout",
      enter: "卢吉道步行径免费，不用预约。上山可坐山顶缆车（建议官网预约）或 15 路巴士。从凌霄阁沿卢吉道走约 10–15 分钟到观景缺口。",
      duration: "1.5–2 小时（含上山）",
      note: "不要只去凌霄阁排队。8 月底日落大约 18:50，建议 17:30 后到。山路有蚊，带薄外套。雨天路滑。",
      xhs: ["卢吉道观景台", "太平山卢吉道日落", "卢吉道情侣"],
      photo: "Hong Kong Night Skyline.jpg",
      img: "photos/lugard.jpg",
      fallback: "#1d3a4a",
      map: "Lugard Road Lookout Victoria Peak",
      lat: 22.2712,
      lng: 114.1482,
      day: 1
    },
    {
      id: "starferry",
      city: "hk",
      area: "维港",
      name: "天星小轮",
      en: "Star Ferry",
      enter: "中环天星码头 ↔ 尖沙咀天星码头。现场买票或拍八达通，不用预约，几分钟一班。",
      duration: "单程约 10 分钟",
      note: "坐上层、靠海一侧。手机广角别开太狠。风大，帽子和薄外套收好。",
      xhs: ["天星小轮拍照", "天星小轮上层", "维港天星小轮"],
      photo: "2019-08-07 A Star Ferry on Victoria Harbour at night (1).jpg",
      img: "photos/starferry.jpg",
      fallback: "#2c5f6e",
      map: "Star Ferry Tsim Sha Tsui Pier",
      lat: 22.2937,
      lng: 114.1684,
      day: 1
    },
    {
      id: "harbour",
      city: "hk",
      area: "尖沙咀",
      name: "钟楼 · 维港海滨",
      en: "Tsim Sha Tsui Promenade",
      enter: "天星小轮下船即到，或港铁尖沙咀站 / 尖东站。海滨和钟楼外观免费，不用预约。",
      duration: "45 分钟–1 小时",
      note: "幻彩咏香江大约 20:00。晚上人多，沿堤岸往西九方向会疏一点。8 月很热，拍完可进海港城。",
      xhs: ["尖沙咀钟楼夜景", "维港海滨拍照", "幻彩咏香江"],
      photo: "Former Kowloon-Canton Railway Clock Tower (Hong Kong).jpg",
      img: "photos/harbour.jpg",
      fallback: "#0f2740",
      map: "Tsim Sha Tsui Clock Tower Hong Kong",
      lat: 22.2938,
      lng: 114.1696,
      day: 1
    },
    {
      id: "mplus",
      city: "hk",
      area: "西九",
      name: "M+ 博物馆",
      en: "M+",
      enter: "尖沙咀海滨向西步行 15–20 分钟，或港铁柯士甸站。艺术公园和外观免费、不用预约。进馆要门票，周末建议官网提前买。",
      duration: "园区 40 分钟；进馆约 1.5 小时",
      note: "只拍外观和园区不必买票。台风或暴雨可把这里当室内备选。馆内按展览规定，通常不能用闪光灯。",
      xhs: ["M+博物馆拍照", "西九M+大字", "M+艺术公园"],
      photo: "M+, West Kowloon, Hong Kong.jpg",
      img: "photos/mplus.jpg",
      fallback: "#4a5560",
      map: "M+ Museum West Kowloon",
      lat: 22.3017,
      lng: 114.1570,
      day: 1
    },
    {
      id: "monster",
      city: "hk",
      area: "鲗鱼涌",
      name: "海山楼（怪兽大厦）",
      en: "Yick Cheong Building",
      enter: "港铁太古站 D 出口步行约 5 分钟，英皇道 1028 号一带。这是民居天井，没有门票，也不能预约，不是景区。",
      duration: "10–20 分钟",
      note: "安静拍、不挡路、不用灯、不躺、不喊。有时会劝离，尊重即走。不要跟居民对拍。",
      xhs: ["海山楼怪兽大厦", "鲗鱼涌海山楼拍照", "怪兽大厦天井"],
      photo: "Looking upward at the Yick Cheong Building, 13 June 2019.jpg",
      img: "photos/monster.jpg",
      fallback: "#d4786a",
      map: "Yick Cheong Building Quarry Bay",
      lat: 22.2850,
      lng: 114.2164,
      day: 3
    },
    {
      id: "mongkok",
      city: "hk",
      area: "旺角",
      name: "弥敦道天桥",
      en: "Nathan Road Footbridge",
      enter: "港铁旺角站 E 出口一带天桥，或豉油街、西洋菜南街。公共街道，免费，不用预约。",
      duration: "30–40 分钟",
      note: "8 月下午暴晒，建议吃饭前后或晚上再去。人多、注意随身物品。天桥上别长时间挡路。",
      xhs: ["弥敦道天桥夜景", "旺角天桥拍照", "旺角霓虹"],
      photo: "HK MK 旺角 Mongkok 彌敦道 Nathan Road n Mong Kok Road footbridge n blue Subaru car November 2025 N13P 01.jpg",
      img: "photos/mongkok.jpg",
      fallback: "#7a1f2b",
      map: "Nathan Road Mong Kok footbridge",
      lat: 22.3193,
      lng: 114.1697,
      day: 3
    },
    {
      id: "disney",
      city: "hk",
      area: "大屿山",
      name: "香港迪士尼乐园",
      en: "Hong Kong Disneyland",
      enter: "必须提前购买指定日期门票（官网或 Klook），8 月底现场很容易没有。港铁欣澳站换乘迪士尼线，开园前到。可选付费快速通行。",
      duration: "一整天（约 8–10 小时）",
      note: "出发前下载官方 App，看排队和巡游时间。中午湿热，多进室内。城堡和大街人少时先拍。行李尽量少带。",
      xhs: ["香港迪士尼城堡拍照", "港迪美国小镇大街", "港迪城堡情侣"],
      photo: "Hong Kong Disneyland Castle.jpg",
      img: "photos/disney.jpg",
      fallback: "#2f6b4f",
      map: "Hong Kong Disneyland Castle",
      lat: 22.3132,
      lng: 114.0415,
      day: 2
    },
    {
      id: "stpaul",
      city: "mo",
      area: "澳门半岛",
      name: "大三巴牌坊",
      en: "Ruins of St. Paul's",
      enter: "住半岛可步行，或巴士到大三巴／板樟堂街。牌坊广场免费，不用预约。牌坊后博物馆若开放，可能收小额门票。",
      duration: "30–40 分钟",
      note: "请第 4 天 8:30 前到。11:00 后几乎拍不到两人。侧拍、低机位，不要站正中间跟人堆叠在一起。",
      xhs: ["大三巴清晨拍照", "大三巴情侣机位", "大三巴牌坊侧拍"],
      photo: "Ruins of Saint Paul's.jpg",
      img: "photos/stpaul.jpg",
      fallback: "#c4b49a",
      map: "Ruins of St Paul's Macau",
      lat: 22.1974,
      lng: 113.5407,
      day: 4
    },
    {
      id: "paixao",
      city: "mo",
      area: "澳门半岛",
      name: "恋爱巷",
      en: "Travessa da Paixão",
      enter: "大三巴牌坊右侧步行约 2 分钟。公共巷弄，免费，不用预约。",
      duration: "15–20 分钟",
      note: "巷子很短，排队拍照请快。旁边疯堂斜巷人更少、墙面同样好拍。不要堵住整条巷。",
      xhs: ["澳门恋爱巷", "恋爱巷路牌", "疯堂斜巷"],
      photo: "Travessa da Paixão.jpg",
      img: "photos/paixao.jpg",
      fallback: "#e8b4a2",
      map: "Travessa da Paixão Macau",
      lat: 22.1970,
      lng: 113.5403,
      day: 4
    },
    {
      id: "senado",
      city: "mo",
      area: "澳门半岛",
      name: "议事亭前地 · 玫瑰堂",
      en: "Senado Square & St. Dominic's",
      enter: "大三巴沿大三巴街往下走 8–10 分钟。广场免费。玫瑰堂通常免费参观，不用预约；保持安静，不要开闪光灯。",
      duration: "40 分钟",
      note: "和大三巴、恋爱巷是同一条步行线，不要拆开跑。正午地面反光强、人多，早晨或晚饭后更合适。",
      xhs: ["议事亭前地波浪纹", "玫瑰堂澳门拍照", "议事亭前地"],
      photo: "Largo do Senado 1110301.jpg",
      img: "photos/senado.jpg",
      fallback: "#d4a017",
      map: "Senado Square Macau",
      lat: 22.1935,
      lng: 113.5399,
      day: 4
    },
    {
      id: "penha",
      city: "mo",
      area: "澳门半岛",
      name: "主教山小堂",
      en: "Penha Chapel",
      enter: "巴士到西望洋圣堂／主教山，或打的。小堂和观景台免费，不用预约。进堂请衣着端庄。",
      duration: "45 分钟",
      note: "山路有点陡。第 3 天下午大三巴人最多时，改来这里更值。风大，注意安全，不要翻越栏杆。",
      xhs: ["主教山小堂", "西望洋圣堂拍照", "主教山情侣"],
      photo: "Capela de Nossa Senhora da Penha (Macau) 01.JPG",
      img: "photos/penha.jpg",
      fallback: "#8fa3b0",
      map: "Capela de Nossa Senhora da Penha Macau",
      lat: 22.1865,
      lng: 113.5369,
      day: 3
    },
    {
      id: "parisian",
      city: "mo",
      area: "路氹",
      name: "巴黎人 · 伦敦人",
      en: "The Parisian & The Londoner",
      enter: "酒店公共区域免费进入，不用预约。巴黎人花园大约 10:00 开门。铁塔观景台若收费，以现场告示为准。可坐氹仔免费接驳或酒店穿梭巴士。",
      duration: "1–1.5 小时",
      note: "晚上铁塔整点灯光更好看。台风天室内走廊和商场可当备选。赌场区域注意着装，部分地方限制拍照。",
      xhs: ["澳门巴黎人铁塔", "伦敦人天桥看铁塔", "巴黎人花园"],
      photo: "The Parisian Macao 30-01-2023(1).jpg",
      img: "photos/parisian.jpg",
      fallback: "#3b2d4a",
      map: "The Parisian Macao",
      lat: 22.1454,
      lng: 113.5636,
      day: 3
    },
    {
      id: "taipa",
      city: "mo",
      area: "氹仔",
      name: "官也街",
      en: "Rua do Cunha",
      enter: "氹仔市区步行即到，近手信店和葡挞店。公共街道，免费，不用预约。",
      duration: "30–40 分钟",
      note: "主要为了吃和手信，不是第一出片点。周末下午极挤。晚上灯亮起来更有氛围。看管背包。",
      xhs: ["官也街夜景", "氹仔官也街", "官也街手信"],
      photo: "Rua do Cunha 19-03-2024.jpg",
      img: "photos/taipa.jpg",
      fallback: "#5c4033",
      map: "Rua do Cunha Taipa",
      lat: 22.1527,
      lng: 113.5559,
      day: 4
    }
  ],
  days: [
    {
      id: 1,
      title: "香港岛 + 维港",
      stay: "尖沙咀",
      from: "深圳福田口岸",
      where: "坚尼地城、港大、中环、太平山、维港",
      path: "福田口岸 → 坚尼地城 → 港大 → 中环大馆 / 半山 → 卢吉道日落 → 天星小轮 → 维港钟楼",
      prep: [
        { item: "游客版八达通加到手机钱包", need: "建议提前", xhs: "八达通游客版" },
        { item: "山顶缆车", need: "建议官网预约；也可坐 15 路巴士不用预约", xhs: "山顶缆车预约" },
        { item: "坚尼地城、港大、大馆、半山扶梯、天星小轮、维港", need: "免费，不用预约" },
        { item: "兰芳园午饭", need: "不用订，现场排队" }
      ],
      beats: [
        { id: "d1a", time: "08:00", type: "commute", mode: "深圳地铁", name: "4 / 10 号线 → 福田口岸", lat: 22.5204, lng: 114.0682, cost: 6, detail: "打开深圳地铁 App，或微信 / 支付宝乘车码。坐 4 号线或 10 号线，到「福田口岸」下车，跟着「往香港」上楼。不用另买票。" },
        { id: "d1b", time: "08:15", type: "commute", mode: "过关步行", name: "福田口岸过关（出闸落马洲站）", lat: 22.5150, lng: 114.0660, cost: 0, detail: "这不是坐车，是过关。先过深圳边检出内地，走过廊桥，再过香港入境处。出闸就是香港的落马洲地铁站。带好通行证和身份证，拉箱子走有「行李」字样的通道。" },
        { id: "d1c", time: "08:50", type: "commute", mode: "港铁", name: "落马洲 → 金钟 → 坚尼地城 · 约 65 分钟", lat: 22.2813, lng: 114.1289, cost: 28, detail: "出闸后拍八达通进站。先坐东铁线，方向选金钟。大约 50 分钟到金钟，换成港岛线，往「坚尼地城」方向坐到终点。全程不用买纸质票。" },
        { id: "d1kt", time: "10:00", type: "spot", name: "坚尼地城", spotId: "kennedy", cost: 0, detail: "港铁坚尼地城站 C 出口。先去西宁街拍游泳池那栋白楼，再沿海边走到卑路乍湾。外观免费拍，不用买票。泳池不要翻栏杆。大约逛 1 小时。" },
        { id: "d1hk", time: "10:55", type: "commute", mode: "港铁", name: "坚尼地城 → 香港大学 · 约 3 分钟", lat: 22.2840, lng: 114.1378, cost: 5, detail: "还是港岛线，一站路，从坚尼地城坐到香港大学站。拍八达通，两三分钟就到。" },
        { id: "d1hku", time: "11:00", type: "spot", name: "香港大学", spotId: "hku", cost: 0, detail: "从港大站 A1 出口上校园。免费逛，不用预约。主要拍本部大楼红砖和陆佑堂。课室、图书馆别进。校园有坡，穿运动鞋。" },
        { id: "d1cc", time: "11:50", type: "commute", mode: "港铁", name: "香港大学 → 中环 · 约 8 分钟", lat: 22.2819, lng: 114.1582, cost: 8, detail: "港岛线往东坐到中环。出站走去大馆，大概再走几分钟。" },
        { id: "d1d", time: "12:00", type: "spot", name: "大馆", spotId: "taikwun", cost: 0, detail: "中环旧警察总部改的园区，红砖很好拍。园区免费，不用预约。大约逛 1 小时。里面冷气很足，可带薄外套。" },
        { id: "d1e", time: "13:10", type: "commute", mode: "步行", name: "荷李活道 → 嘉咸街 · 约 8 分钟", lat: 22.2830, lng: 114.1547, cost: 0, detail: "不用坐车。从大馆沿着荷李活道走到嘉咸街，七八分钟就接到半山扶梯。" },
        { id: "d1f", time: "13:20", type: "spot", name: "半山扶梯 · 石板街", spotId: "escalator", cost: 0, detail: "公共扶梯，免费。大约上午 10 点以后是往上走的。拍两张就走，别长时间占台阶。" },
        { id: "d1g", time: "14:20", type: "meal", name: "午饭 · 兰芳园（中环结志街）", lat: 22.2839, lng: 114.1550, xhs: "兰芳园 中环", cost: 100, img: "photos/lanfong.jpg", photo: "HK 中環 Central 結志街 Gage Street shop Lan Fong Yuen Cafe Restaurant March 2021 SS2.jpg", detail: "中环老茶餐厅，丝袜奶茶有名。不用订座，排队点单。两人午饭大概一人一百出头。吃完可以在附近慢慢走到缆车站。" },
        { id: "d1h", time: "16:00", type: "commute", mode: "山顶缆车", name: "花园道上山（可改 15 路巴士）", lat: 22.2774, lng: 114.1544, cost: 88, detail: "从中环走到花园道缆车站。建议提前网上订山顶缆车；不想订就改坐 15 路巴士，拍八达通，便宜很多。上山是为了走卢吉道看日落，不要只排凌霄阁。买往返票的话，下山不用再买。" },
        { id: "d1i", time: "16:50", type: "spot", name: "卢吉道观景台", spotId: "lugard", cost: 0, detail: "从凌霄阁沿卢吉道走十几分钟，有缺口能看维港日落。8 月底日落大约 18:50，尽量 17:30 后到。山路有蚊，雨天路滑。" },
        { id: "d1j", time: "19:15", type: "commute", mode: "山顶缆车", name: "下山至中环", lat: 22.2774, lng: 114.1544, cost: 0, detail: "原路坐缆车回中环。如果上山买的是往返票，这里不用再花钱。下来后去天星码头坐船。" },
        { id: "d1k", time: "19:40", type: "commute", mode: "天星小轮", name: "中环 → 尖沙咀 · 约 10 分钟", lat: 22.2937, lng: 114.1684, cost: 5, detail: "中环天星码头坐船到尖沙咀，几分钟一班。拍八达通，几块钱。坐上层、靠海的一边。风大，帽子收好。" },
        { id: "d1l", time: "20:00", type: "spot", name: "钟楼 · 维港海滨", spotId: "harbour", cost: 0, detail: "下船就是钟楼和海滨，免费。晚上约 20:00 有幻彩咏香江灯光秀。人多的话可以沿堤岸往西走一点。" },
        { id: "d1m", time: "21:15", type: "hotel", name: "尖沙咀酒店", lat: 22.2976, lng: 114.1722, detail: "今晚住尖沙咀。入住出示通行证，押金用银联卡刷预授权。花销已算在酒店房费里，这里不再单列。" }
      ]
    },
    {
      id: 2,
      title: "港迪",
      stay: "尖沙咀",
      from: "尖沙咀酒店",
      where: "香港迪士尼（一整天）",
      path: "尖沙咀 → 美孚 / 屯马线 → 欣澳 → 迪士尼线 → 园内一整天 → 回尖沙咀",
      prep: [
        { item: "香港迪士尼指定日门票", need: "必须提前买（官网或 Klook），8 月底现场很容易没有", xhs: "香港迪士尼门票" },
        { item: "Disney 官方 App", need: "出发前下载，看排队和巡游" },
        { item: "付费快速通行", need: "可选，现场或网上" },
        { item: "园内午饭晚饭", need: "不用订，App 看排队" }
      ],
      beats: [
        { id: "d2a", time: "08:10", type: "commute", mode: "港铁", name: "尖沙咀 → 欣澳 → 迪士尼 · 约 55–70 分钟", lat: 22.3132, lng: 114.0415, cost: 30, detail: "拍八达通。荃湾线从尖沙咀坐到美孚，换成屯马线到欣澳，再换成迪士尼线。全程大约一小时。开园前到比较好拍城堡。" },
        { id: "d2b", time: "09:20", type: "spot", name: "香港迪士尼乐园", spotId: "disney", cost: 699, detail: "门票必须提前在官网或 Klook 买指定日期，8 月底现场很容易没有。进园先拍城堡和美国小镇大街。下载官方 App 看排队。花销按普通日门票估算，实际以你买的票为准。" },
        { id: "d2c", time: "12:30", type: "meal", name: "午饭 · 美国小镇大街", lat: 22.3136, lng: 114.0428, xhs: "港迪美国小镇大街吃饭", cost: 150, img: "photos/disney-lunch.jpg", photo: "Disneyland Hong Kong - Main Street USA IMG 5510.JPG", detail: "在园内吃，不用订座。中午人多，可以先玩再吃，或看 App 里哪家排队短。一人大约 150 港币。" },
        { id: "d2d", time: "18:00", type: "meal", name: "晚饭 · 园内", lat: 22.3128, lng: 114.0410, xhs: "香港迪士尼晚餐", cost: 180, img: "photos/disney-dinner.jpg", photo: "Hong Kong Disneyland Castle.jpg", detail: "继续在园内解决。傍晚再拍一版城堡暖光，晚上可看烟花后再走。" },
        { id: "d2e", time: "20:30", type: "commute", mode: "港铁", name: "迪士尼 → 尖沙咀 · 约 60 分钟", lat: 22.2976, lng: 114.1722, cost: 30, detail: "原路返回：迪士尼线到欣澳，再转屯马线或东涌线回尖沙咀。大约一小时。拍八达通。" },
        { id: "d2f", time: "21:40", type: "hotel", name: "尖沙咀酒店", lat: 22.2976, lng: 114.1722, detail: "还住尖沙咀，不用换酒店。房费不含在当天花销里。" }
      ]
    },
    {
      id: 3,
      title: "港风 → 澳门",
      stay: "路氹",
      from: "尖沙咀（退房）",
      where: "海山楼、旺角、主教山、路氹",
      path: "海山楼 → 旺角早茶 / 天桥 → 上环坐船 → 主教山 → 巴黎人 → 官也街",
      prep: [
        { item: "尖沙咀酒店退房", need: "行李寄存或带上船" },
        { item: "富临饭店早茶", need: "周末建议提前订位", xhs: "富临饭店订位" },
        { item: "喷射飞航 上环 → 澳门外港", need: "必须提前订票", xhs: "喷射飞航订票" },
        { item: "海山楼、弥敦道天桥、主教山、巴黎人、官也街", need: "免费，不用预约" }
      ],
      beats: [
        { id: "d3a", time: "08:00", type: "hotel", name: "尖沙咀酒店退房", lat: 22.2976, lng: 114.1722, detail: "今天退房。行李可以先寄存在酒店，下午去码头再取；或者直接拖上船去澳门。房费不含在当天花销里。" },
        { id: "d3b", time: "08:10", type: "commute", mode: "港铁", name: "尖沙咀 → 旺角 → 太古 · 约 25 分钟", lat: 22.2850, lng: 114.2164, cost: 12, detail: "拍八达通。荃湾线从尖沙咀坐到旺角，换成观塘线到太古。大概 25 分钟。太古站 D 出口走几分钟就是海山楼。" },
        { id: "d3c", time: "08:40", type: "spot", name: "海山楼（怪兽大厦）", spotId: "monster", cost: 0, detail: "这是民居天井，不是景区，免费，也不能预约。安静拍几张就走，别挡路、别喊、别用灯。有人劝离就离开。" },
        { id: "d3d", time: "09:10", type: "commute", mode: "港铁", name: "太古 → 旺角 · 约 20 分钟", lat: 22.3193, lng: 114.1697, cost: 10, detail: "观塘线从太古坐回旺角，大约 20 分钟。去富临吃早茶。" },
        { id: "d3e", time: "09:40", type: "meal", name: "早茶 · 富临饭店（旺角）", lat: 22.3178, lng: 114.1702, xhs: "富临饭店 旺角", cost: 180, img: "photos/fulum.jpg", photo: "Fung Lum Restaurant (Hong Kong) 01.jpg", detail: "旺角茶楼，推车点心。周末建议提前订位，不然要排队。两人早茶大概一人 150–200 港币。" },
        { id: "d3f", time: "11:00", type: "spot", name: "弥敦道天桥", spotId: "mongkok", cost: 0, detail: "旺角站附近天桥，免费拍街景和车流。人多，看管背包，别长时间挡路。" },
        { id: "d3g", time: "12:10", type: "commute", mode: "港铁 + 步行", name: "旺角 → 中环，再走到上环码头 · 约 25 分钟", lat: 22.2878, lng: 114.1512, cost: 10, detail: "荃湾线从旺角坐到中环，出站再走到上环港澳码头。带着行李的话走慢一点。船票提前买好，到码头换票进闸。" },
        { id: "d3h", time: "13:00", type: "commute", mode: "喷射飞航", name: "上环 → 澳门外港 · 约 60 分钟", lat: 22.1967, lng: 113.5595, cost: 210, detail: "坐船去澳门。上环港澳码头上船，大约 1 小时到澳门外港客运码头。票要提前在官网或携程买，尽量可改签。周末容易满。船上有座位，行李放脚边或行李架。" },
        { id: "d3i", time: "14:20", type: "commute", mode: "的士", name: "外港 → 主教山 · 约 15 分钟", lat: 22.1865, lng: 113.5369, cost: 70, share: true, detail: "下船后直接在码头外打车去主教山。澳门路有坡，又拖着行李，别挤巴士。上车先问「打表吗」。这一趟是按一辆车算，两个人分摊。港币现金或支付宝一般都能付。" },
        { id: "d3j", time: "14:40", type: "spot", name: "主教山小堂", spotId: "penha", cost: 0, detail: "小堂和观景台免费，不用预约。能看海，人比大三巴少。进堂衣着端庄。山路有点陡。" },
        { id: "d3k", time: "16:40", type: "commute", mode: "的士", name: "主教山 → 路氹巴黎人 · 约 20 分钟", lat: 22.1454, lng: 113.5636, cost: 80, share: true, detail: "再打车去路氹的巴黎人。大约 20 分钟。同样先问打表，按一辆车算。" },
        { id: "d3l", time: "17:10", type: "spot", name: "巴黎人 · 伦敦人", spotId: "parisian", cost: 0, detail: "酒店公共区域免费进。巴黎人花园大约 10 点开门。晚上铁塔灯光更好看。赌场里部分地方不能拍。" },
        { id: "d3m", time: "20:30", type: "meal", name: "晚饭 · 巴黎人 / 伦敦人", lat: 22.1458, lng: 113.5628, xhs: "澳门巴黎人餐厅", cost: 150, img: "photos/parisian.jpg", photo: "The Parisian Macao 30-01-2023(1).jpg", detail: "在商场里找家餐厅就行，不用订米其林。一人大约 150 港币。澳门能直接用港币或支付宝。" },
        { id: "d3n", time: "21:30", type: "commute", mode: "的士", name: "路氹 → 官也街 · 约 10 分钟", lat: 22.1527, lng: 113.5559, cost: 50, share: true, detail: "酒店接驳车如果有，免费；没有就打的，十来分钟。按一辆车算。" },
        { id: "d3o", time: "21:40", type: "spot", name: "官也街", spotId: "taipa", cost: 0, detail: "氹仔老街，买手信、吃点心。晚上灯亮起来更有氛围。主要不是拍大片的地方，看管背包。" },
        { id: "d3p", time: "22:20", type: "hotel", name: "路氹酒店", lat: 22.1458, lng: 113.5628, detail: "今晚住路氹，方便铁塔，明天清晨打的去大三巴。房费不含在当天花销里。" }
      ]
    },
    {
      id: 4,
      title: "澳门清晨 → 蛇口",
      stay: "回深圳",
      from: "路氹酒店",
      where: "大三巴、恋爱巷、议事亭，中午船回蛇口",
      path: "路氹 → 大三巴 → 恋爱巷 → 议事亭 → 外港码头 → 船回蛇口过关",
      prep: [
        { item: "大三巴、恋爱巷、议事亭", need: "免费不用预约，请 8:30 前到大三巴" },
        { item: "大利来猪扒包", need: "不用订，早上去排队更短" },
        { item: "喷射飞航 澳门外港 → 蛇口", need: "必须提前订票，留过关和去机场时间", xhs: "澳门到蛇口船票" },
        { item: "回内地过关", need: "通行证 + 深圳边检，不要再进香港" }
      ],
      beats: [
        { id: "d4a", time: "07:30", type: "commute", mode: "的士", name: "路氹 → 大三巴 · 约 25 分钟", lat: 22.1974, lng: 113.5407, cost: 90, share: true, detail: "早上从路氹酒店打车去大三巴，大约 25 分钟。有酒店接驳也可以坐。按一辆车算。请 8 点前到，人少才好拍。" },
        { id: "d4b", time: "08:00", type: "spot", name: "大三巴牌坊", spotId: "stpaul", cost: 0, detail: "免费，不用预约。清晨人少。不要站正中间跟旅游团挤在一起，侧拍、低机位更干净。11 点后人会非常多。" },
        { id: "d4c", time: "08:40", type: "commute", mode: "步行", name: "去恋爱巷 · 约 2 分钟", lat: 22.1970, lng: 113.5403, cost: 0, detail: "大三巴牌坊右侧走两分钟就到。不用坐车。" },
        { id: "d4d", time: "08:42", type: "spot", name: "恋爱巷", spotId: "paixao", cost: 0, detail: "很短的一条巷，免费。排队拍照请快。旁边疯堂斜巷人更少。" },
        { id: "d4e", time: "09:10", type: "commute", mode: "步行", name: "大三巴街下山 · 约 8 分钟", lat: 22.1935, lng: 113.5399, cost: 0, detail: "沿着大三巴街往下走就到议事亭前地。同一条步行线，不用打车。" },
        { id: "d4f", time: "09:20", type: "spot", name: "议事亭前地 · 玫瑰堂", spotId: "senado", cost: 0, detail: "波浪纹地面和玫瑰堂，免费。玫瑰堂里保持安静，不要开闪光灯。" },
        { id: "d4g", time: "10:20", type: "meal", name: "猪扒包 · 大利来（议事亭附近）", lat: 22.1938, lng: 113.5405, xhs: "大利来猪扒包", cost: 40, img: "photos/tailei.jpg", photo: "TAI LEI LOI KEI, Macau, 招牌豬扒飽, 澳門大利來記豬扒飽, 大三巴街, 澳門 (17103261017).jpg", detail: "议事亭附近的猪扒包店，不用订，排队买。一个大约几十港币，当早点刚好。" },
        { id: "d4h", time: "11:30", type: "commute", mode: "的士", name: "议事亭 → 外港码头 · 约 12 分钟", lat: 22.1967, lng: 113.5595, cost: 50, share: true, detail: "打车去外港客运码头坐船。大约 12 分钟。按一辆车算。提前留一点时间换票进闸。" },
        { id: "d4i", time: "12:00", type: "commute", mode: "喷射飞航", name: "澳门外港 → 蛇口 · 约 60 分钟", lat: 22.4792, lng: 113.9128, cost: 210, detail: "坐船回深圳蛇口邮轮母港，大约 1 小时。票要提前买。过关后就是深圳，不用再进香港。回北京机票不要订太晚。" },
        { id: "d4j", time: "13:10", type: "commute", mode: "过关步行", name: "蛇口邮轮母港过关", lat: 22.4792, lng: 113.9128, cost: 0, detail: "下船后过香港以外的回内地边检，用通行证 + 深圳边检。出关后可以坐深圳地铁去机场或找朋友。" }
      ]
    }
  ]
};

